### ISSUE TITLE
[BUG] Vanilla spawn masker by catching the host will also notify

### ISSUE THREAD

**Issue by CoolLKKPS** [03-JS/ControlCompanyDetector#4]
BUG!

**Comment by 03-JS** [comment]
Could you give any more details about the bug?

**Comment by CoolLKKPS** [comment]
so uh

**Comment by CoolLKKPS** [comment]
a vanilla masker spawned, catched a player, and turned player catched the host, and notify

**Comment by CoolLKKPS** [comment]
and the first player just rage dc after converted, btw MoreCompany lobby

**Comment by 03-JS** [comment]
I just tested it and it does notify when it shouldn't, I'm working on a fix rn

**Comment by CoolLKKPS** [comment]
nice! feel free to close this issue, happy to help!

**Comment by 03-JS** [comment]
Fixed! - [v3.1.1](https://thunderstore.io/c/lethal-company/p/JS03/Control_Company_Detector/)
