### ISSUE TITLE
More Monsters Mods Trigger This Mod [Bug]

### ISSUE THREAD

**Issue by Urusovite** [03-JS/ControlCompanyDetector#5]
The more monsters mod appears to trigger this mod's "[enemy] spawned by player" message even though nobody is spawning monsters. As a guy who hosts, I actually love your mod because it let everyone know I do NOT use control company but I always run lethal escape and more monsters with more company mod. Unfortunately, now I'm getting yelled at in lobbies for control company when I do not have it. I should note this happened with your most recent update as of Feb 21st 2024

More Monsters:
https://thunderstore.io/c/lethal-company/p/QuokkaCrew/MoreMonsters/

https://github.com/0xjclar/MoreMonsters

This bug/conflict also triggers for MonstersPlus, a substitute I tried:

https://thunderstore.io/c/lethal-company/p/ZeroExAlt/MonstersPlus/

It appears any mod that affects spawn rates will say "[enemy] spawned by player"

**Comment by 03-JS** [comment]
Yeah sadly there's nothing I can do about it atm, any mod that changes how monsters spawn will trigger it. I'm gonna set that feature off by default to avoid having issues like this often

**Comment by 03-JS** [comment]
Actually nevermind, I'm going to change it so no message pops up when Control Company hasn't been detected, that should hopefully solve the issue

**Comment by 03-JS** [comment]
Problem hopefully solved in [v3.2.1](https://thunderstore.io/package/download/JS03/Control_Company_Detector/3.2.1/).

The "A [enemy name] has been spawned by a player" warning now only appears when you host a lobby with my mod

**Comment by Urusovite** [comment]
Oh, nice appreciate it. I will test it tonight!

**Comment by 03-JS** [comment]
Let me know how it goes. Latest version is 3.2.2, but it's basically the same as 3.2.1

**Comment by Urusovite** [comment]
> Let me know how it goes. Latest version is 3.2.2, but it's basically the same as 3.2.1

It works. Had to delete previous config and no more problems

**Comment by 03-JS** [comment]
> > Let me know how it goes. Latest version is 3.2.2, but it's basically the same as 3.2.1
> 
> It works. Had to delete previous config and no more problems

Nice! Glad to hear that. Well if you have any other issues in the future, you know where to report 'em
