### ISSUE TITLE
[Question] can u explain what exactly about "additional info message" that from "Show info message" config option

### ISSUE THREAD

**Issue by CoolLKKPS** [03-JS/ControlCompanyDetector#6]
same as topic

**Comment by CoolLKKPS** [comment]
additional info message should be only Spawn detection alert message if im right?

**Comment by 03-JS** [comment]
> additional info message should be only Spawn detection alert message if im right?

Sort of. The info message will only appear when hosting a lobby with the Detect enemy spawning as host option enabled if you have a mod that changes how enemies spawn

**Comment by 03-JS** [comment]
It's basically a message that pops up and tells you "hey, you have this mod installed which means enemy spawning detection when hosting won't work". Hope I was able to answer your question

**Comment by CoolLKKPS** [comment]
hmm i was thinking u added more features in this mod, but might be in the future?
sug move this option to the Spawn detection category if u plan to add more features, but uh that will be a anti-cheat mod i think, ur updates are so frequent that my modpack can't keep up with this cadence, but hey, good job!

i got 140 mods with 1.04 GB from my modpack, btw

**Comment by 03-JS** [comment]
Yeah I want to take a break from the constant updates too, v3.3.0 should hopefully be the latest one for a while

**Comment by 03-JS** [comment]
> hmm i was thinking u added more features in this mod, but might be in the future? sug move this option to the Spawn detection category if u plan to add more features, but uh that will be a anti-cheat mod i think, ur updates are so frequent that my modpack can't keep up with this cadence, but hey, good job!
> 
> i got 140 mods with 1.04 GB of my modpack, btw

I decided to put it under hosting becuase well, it only affects you when hosting. But no I haven't added any more features like that, everything I've added or updated can be checked in the [changelog](https://thunderstore.io/c/lethal-company/p/JS03/Control_Company_Detector/changelog/).

Also I have thought about making an "Anti-cheat" mod, but like I said I just wanna take a break rn. Maybe in the future I will make something like that, who knows

**Comment by CoolLKKPS** [comment]
> I decided to put it under hosting becuase well, it only affects you when hosting. But no I haven't added any more features like that, everything I've added or updated can be checked in the [changelog](https://thunderstore.io/c/lethal-company/p/JS03/Control_Company_Detector/changelog/).
> 
> Also I have thought about making an "Anti-cheat" mod, but like I said I just wanna take a break rn. Maybe in the future I will make something like that, who knows

actually Host Fixes also are an anti-cheat mod, but don't have many more features for modded clients; i read the changelog, but uh just confuse about how this option work in that time since u did change so much things
i know a community anti-cheat from different game and i still appreciate that, "No Mutants Allowed" made by TDLQ for PAYDAY 2 even it has a lot false report, but the point is, that mod check every data from ur client, and it also have database, if the behavior or data from other clients are mismatch, i will receive a warning, that anti-cheat mod is really hard to made, specially PD2 support modding

**Comment by CoolLKKPS** [comment]
but anyway, going to update my modpack now, really thx for ur mod!
