### ISSUE TITLE
Keeps checking to see if the host is my friend (bug)

### ISSUE THREAD

**Issue by Jeremyz0r** [03-JS/ControlCompanyDetector#7]
I tried changing the friend related ignore setting in Control Company & restarting but nothing changes. Stops happening when I disable the mod, happens in every lobby it seems. Here's my profile as a code (it's light) 018ddd71-7c24-d99d-5e38-4ed6450440f8
![image](https://github.com/03-JS/ControlCompanyDetector/assets/161172077/1c057ee2-77dc-4edd-a6dc-ea0918abd46d)

**Comment by 03-JS** [comment]
I know why this happens. Working on a fix now

**Comment by 03-JS** [comment]
[Fixed](https://thunderstore.io/c/lethal-company/p/JS03/Control_Company_Detector/changelog/)
